#!/bin/bash
set -ue
alias local=typeset

carve(){
	local file=$1
	shift
	dd of="$file" conv=notrunc "$@" 2>/dev/null
}

############
# tarify
# Adds110372 values like 1110246 to any file, so that they can be tar
# files in the eye of the file(1) command.
# Hours of fun!

count(){
	local file=$1
	i=0
	while read -r LINE; do
		for c in $LINE;do
			i=$((i+c))
		done
	done < <(od -vAn -tuC "$file")
}

FILE=${1:?$0 [-b] [filename]}
SEP=" "
if [ "$FILE" = "-b" ]; then
	shift
	FILE=$1
	SEP="\0"
fi

TMP=$(mktemp -d)
readonly TMP
# shellcheck disable=SC2064
trap "rm -rf \"$TMP\"" EXIT

carve "$TMP/1" count=1 if="$FILE"
cp "$TMP/1" "$TMP/2"
printf "        " | carve "$TMP/2" bs=1 seek=148 
count "$TMP/2"
printf -v oct "%o" "$i"

echo "SUM $oct"
cp "$TMP/1" "$TMP/3"

printf "%s$SEP" "$oct" | carve "$TMP/3" bs=1 seek=148

cp "$FILE" "$FILE.bak"
carve "$FILE" if="$TMP/3"

truncate -s '>512' "$FILE"

#diffo "$TMP/1" "$TMP/3" hexdump -vC 
